### PR TITLE
[Issue-Fix]: Updated scroll in dynamic layer method to use dimensions of inner dropdown

### LINKED ISSUE #196: Update ScrollInDynamicLayer() to use the size of inner dropdown instead of entire mobile screen
ScrollInDynamicLayer() method in the driver class should get the size(height & width) of the pop-up/inner dropdown/dynamic layer screen instead of getting the size of the whole mobile screen for scrolling.

Need to change this:
public void scrollInDynamicLayer(Direction direction) {
        Dimension dimension = driver.manage().window().getSize();
    }

### PR DESCRIPTION
**Pull request by snehith07**
This PR fixes #196 
Updated scroll in dynamic layer method to use the size of the inner dropdown instead of the entire mobile screen

1. updated method in driver class: scrollInDynamicLayer(Direction direction, WebElement dropDownElement) 
2. Added a scenario using the auto-scroll app to validate the scrollInDynamicLayer() method
3. Removed the previous test scenario available in vodQa.features

### CODE REVIEW

File: src/main/java/com/znsio/teswiz/runner/Driver.java [hunk 1]
```diff
@@ -547,8 +547,8 @@ public void injectMediaToBrowserstackDevice(String uploadFileURL) {
         }
     }
 
-    public void scrollInDynamicLayer(Direction direction) {
-        Dimension dimension = driver.manage().window().getSize();
+    public void scrollInDynamicLayer(Direction direction, WebElement dropDownElement) {
```
Comment (anandbagmar) [inline src/main/java/com/znsio/teswiz/runner/Driver.java:550]: why is the element name dropDownElement?

Comment (snehith07) [reply src/main/java/com/znsio/teswiz/runner/Driver.java:550]: mostly the dynamic layer is an inner dropdown, should I change the name to dynamicLayerElement?
